AWSTemplateFormatVersion : "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  NameForTable:
    Type: String
    Default: UserByCloudFormationYaml
      
Resources : 
  SistemasUsersCL:
      Type : AWS::DynamoDB::Table
      Properties : 
        AttributeDefinitions : 
          -
            AttributeName : "CPF"
            AttributeType : "N"
          -
            AttributeName : "Name"
            AttributeType : "S"
        KeySchema :
          -
            AttributeName : "CPF"
            KeyType : "HASH"
          -
            AttributeName : "Name"
            KeyType : "RANGE"
        TableName : SistemasUsersDyDB
        ProvisionedThroughput : 
          ReadCapacityUnits : "5"
          WriteCapacityUnits : "5"

  LambdaFunctionSistemasUsers:
      Type: AWS::Serverless::Function
      Properties:
        Runtime: python3.9
        Role: arn:aws:iam::167690867954:role/sistemas-Users
        FunctionName: SistemasUsersLambdaFunction
        Handler: function_lambda_users.lambda_handler
        CodeUri: /home/caie/Projects/work/sistemas/users/lambda
        Description: function
