AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function
Resources:
  LambdaFunctionSistemasUser:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Role: arn:aws:iam::167690867954:role/sistemas-Users
      Handler: lambda_handler
      Code: ../lambda/function_lambda_users.py 
      Description: function
