AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function
Resources:
  LambdaFunctionSistemasUser:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Role: arn:aws:iam::167690867954:role/sistemas-Users
      Handler: lfunction_lambda_users.ambda_handler
      Code:
        CodeUri: ../lambda 
      Description: function
