AWSTemplateFormatVersion : "2010-09-09"
Resources : 
  UsersByCloudFormationYaml:
    Type : AWS::DynamoDB::Table
    Properties : 
      AttributeDefinitions : 
        -
          AttributeName : "CPF"
          AttributeType : "N"
        -
          AttributeName : "Name"
          AttributeType : "S"
      KeySchema :
        -
          AttributeName : "CPF"
          KeyType : "HASH"
        -
          AttributeName : "Name"
          KeyType : "RANGE"
      TableName : "UserByCloudFormationYaml"
      ProvisionedThroughput : 
        ReadCapacityUnits : "5"
        WriteCapacityUnits : "5"
